[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true }
api = { path = "../../api" }
consensus = { path = "../../consensus" }
trng = { path = "../../trng" }
hex = { workspace = true }